name: Stevedore fails to install
description: Report an issue related to Stevedore install process
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: Before reporting a bug, please check that is isn't fixed in the [latest release](https://github.com/slonopotamus/stevedore/releases/latest)
  - type: dropdown
    id: version
    attributes:
      label: Stevedore Sersion
      description: What Stevedore version are you trying to install?
      options:
        - 0.0.1
    validations:
      required: true
  - type: input
    id: windows-version
    attributes:
      label: Windows version
      description: |
        What Windows build are you using?
        To find it out, launch `cmd.exe` and copy-paste the first line that it prints
      placeholder: Microsoft Windows [Version 10.0.17763.316]
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: |
        In order to collect installation logs, do the following:
        1. Launch `cmd.exe`
        2. `cd` to directory where Stevedore MSI is located
        3. `msiexec /i <name-of-stevedore.msi> /l+v stevedore.log`
        4. Walk through installer steps to reproduce the bug
        5. Close installer
        6. Open `stevedore.log` located in the same directory with MSI
        7. Copy-paste contents of `stevedore.log` in the textfield below
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Any additional context information you think is relevant
